server:
  port: ${PORT:8070}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5432}/${POSTGRES_DB_NAME:user_crud}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    com.casper.usercrud: info
    root: info
  file:
    name: ${LOGS_DIRECTORY:logs}/user-crud.log
    max-history: 30
    max-size: 10MB
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss.SSS, Europe/Minsk
    rolling-file-name: ${LOGS_DIRECTORY:logs}/archived/user-crud.%d{dd-MM-yyyy}.%i.log
